### ISSUE TITLE
Quarter Cron is not Quarter

### ISSUE THREAD

**Issue by UrsWeberG** [Omega236/ioBroker.valuetrackerovertime#119]
**Describe the bug**  
I expect that the Quarters are Jan-Mar, Apr-Jun, Jul-Sept and Oct-Dec
Now they are Dez-Feb, Mar-Mai, Jun-Aug and Sep-Nov

**To Reproduce**  
Check you Quarter Startvalues when they changed 

**Expected behavior**  
I expect that the Quarters are Jan-Mar, Apr-Jun, Jul-Sept and Oct-Dec

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
1.0.1

**Additional context**  
Please change Line 93 in https://github.com/Omega236/ioBroker.valuetrackerovertime/blob/master/main.js

Should be:
    this.crons.push(cron.schedule("0 0 1 1,4,7,10 *", async () => {
      await this._timeFrameFinished(TimeFrames.Quarter);
    }));

**Comment by Omega236** [comment]
behoben #181
