### ISSUE TITLE
Verbrauchskosten berechnen

### ISSUE THREAD

**Issue by SpezialAgent** [Omega236/ioBroker.valuetrackerovertime#146]
Ist geplant, auch die Kosten der Verbräuche zu berechnen? Also z.B. bei Strombezug (pos. Kosten) und Stromeinspeisung (neu. Kosten == Erstattung).

**Comment by Omega236** [comment]
Ich löse das über ein kleines Blockly:

![grafik](https://github.com/user-attachments/assets/83a6dac8-0261-44d1-815c-01533d050e27)

hier wird von dem Stromzähler jede Differenz genommen, diese mit den Kosten Multipliziert und auf einen neuen Kostenzähler gespeichert.

Diesen neuen Kostenzähler überwache ich wieder mit valuetrackerovertime.

So ist auch sichergestellt, dass Preise geändert werden können und es keine Rückwirkenden Auswirkungen hat
