### ISSUE TITLE
Value current day does not reset

### ISSUE THREAD

**Issue by MeisterQ** [Omega236/ioBroker.valuetrackerovertime#16]
Im logging my total consumption per day (electricity) with a Shelly 3EM.

Im logging the Datapoint Consumption in the Shelly Adapter.

The Datapoint "currentDay" does not reset on daychange.

Most time the values will be addet to the last one. So, at 0:00o'clock the "startvalue" of the day should be set to the current total counter right?

But it still counts up and the value just increase.

![iob1](https://user-images.githubusercontent.com/39710886/112442118-cad5b980-8d4b-11eb-849d-1a40b451a8a7.PNG)
![iob2](https://user-images.githubusercontent.com/39710886/112442121-cb6e5000-8d4b-11eb-9152-377191c0fb96.PNG)

**Comment by Omega236** [comment]
Hello

Do you have error logs at 0:00?

**Comment by MeisterQ** [comment]
> 
> 
> Hello
> 
> Do you have error logs at 0:00?

Sure.


2021-03-26 00:00:00.198  - info: valuetrackerovertime.0 (3208) disable : shelly.0.SHEM-3#DC4F2276473B#1.Total.ConsumedPower
--
2021-03-26 00:00:00.231  - info: valuetrackerovertime.0 (3208) initial (enabled): shelly.0.SHEM-3#DC4F2276473B#1.Total.ConsumedPower
"valuetrackerovertime.0.Verbrauch.03_previousMonths.Before_01_Month" not  found (3) states[id]=null
2021-03-26 00:00:00.257  - info: valuetrackerovertime.0 (3208) initial (enabled): linkeddevices.0.Haus.ConsumedPower

Today i figured out, that on my Total consumption, the Day starting Value changed, but the calculated value didnt. If i click on starting value, hit the ok icon, it refreshes and show the new value from today.

**Comment by MeisterQ** [comment]
I found a solution:

I had Linkeddevices enabled, so, the Adapter had problems to figureout the correct value, because it was enabled on 2 Datapoints.

After disabling the logging at the cloned datapoint, it startet working great.
