### ISSUE TITLE
Cannot load jsonConfig of valuetrackerovertime: Not exists

### ISSUE THREAD

**Issue by dQeLse** [Omega236/ioBroker.valuetrackerovertime#21]
With Admin-Interface 5.1.25 you can't assign datapoints for valuetracker.
this message come up: Cannot load jsonConfig of valuetrackerovertime: Not exists

**Comment by Ricox1975** [comment]
same here

**Comment by Timmer19** [comment]
same here

**Comment by Timmer19** [comment]
same here
