### ISSUE TITLE
problems with adaper linkeddevices

### ISSUE THREAD

**Issue by ChWeiler** [Omega236/ioBroker.valuetrackerovertime#49]
**Describe the bug**  
if objects in adapter Linkeddevices, they are twice in valuetracker

**To Reproduce**  
1. install valuetracker
2. install linkeddevices
3. got to custom settings in an object (not a linkeddevice) and aktivate linkeddevices an give him a name
4. aktivate valuetracker in the custom settings
5. Now both objects in valuetracker: the object and the linkeddevice
6. See error

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/10938014/226933394-67adf58b-ca40-46c0-b953-cac948e39fd8.png)

**Versions:**  
 - Adapter version valuetracker: 
 - Adapter version linkeddevices: 
 - JS-Controller version: js-controller
 - Node version: v16.19.1
 - Operating system: Debian GNU/Linux 11 (bullseye)

**Additional context**

**Comment by Omega236** [comment]
I can confirm that happens.

But the problem happens with the linkeddevice-Adapter with any adapter that uses custom DP settings (like SQL, history ...).

If the settings are set to the LinkedDeviced DP, only this data point will be processed.

**Comment by ChWeiler** [comment]
ok, thank you
