### ISSUE TITLE
Update stable version in repo from 1.0.0 to 1.0.1

### ISSUE THREAD

**Issue by GermanBluefox** [Omega236/ioBroker.valuetrackerovertime#55]
# Think about update stable version to 1.0.1
**Version**: stable=**1.0.0** (34 days old) => latest=**1.0.1** (30 days old)
**Installs**: stable=**98** (45.58%), latest=**60** (27.91%), total=**215**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L2416)

**Comment by mcm1957** [comment]
A kind reminder.
Is there any reason to delay an update of stable revision?

Feel free to drop a simple note if I should trigger an update.

**Comment by mcm1957** [comment]
@Omega236 
Is there any reason to delay updating stable any longer?
Please drop a commit if you know any reason to refrain from updating.

**If there is no response within the next 30 days, we could decide to update anyway.**

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 1.0.1 but the current stable version is already 1.0.1.

So this issue should be closed.
